package hr.fer.zemris.java.custom.scripting.nodes;

/**
 * Interface defining node visitor used for traversing node tree generated by
 * the parser.
 * 
 * @author Lovro Marković
 *
 */
public interface INodeVisitor {

	/**
	 * Method performed when visiting a text node.
	 * 
	 * @param node
	 *            Text node
	 */
	public void visitTextNode(TextNode node);

	/**
	 * Method performed when visiting a for loop node.
	 * 
	 * @param node
	 *            For loop node.
	 */
	public void visitForLoopNode(ForLoopNode node);

	/**
	 * Method performed when visiting an echo node.
	 * 
	 * @param node
	 *            Echo node.
	 */
	public void visitEchoNode(EchoNode node);

	/**
	 * Method performed when visiting a document node.
	 * 
	 * @param node
	 *            Document node.
	 */
	public void visitDocumentNode(DocumentNode node);

}
